### ISSUE TITLE
types missing

### ISSUE THREAD

**Issue by jdilla52** [wanderers-nft/opensea-stream-rs#4]
These's several types that should be updated following the recent-ish updates:
https://docs.opensea.io/reference/stream-api-event-schemas

order-hash
maker(missing from some types)

I have a local version. Happy to push a pr.

**Comment by the-emerald** [comment]
Please do open a PR! tysm in advance

**Comment by jdilla52** [comment]
Does this repo allow for for others to push branches or would you like review a fork?

**Comment by the-emerald** [comment]
You should be able to open up a PR with your fork as the source and our repo as the destination!

**Comment by jdilla52** [comment]
Sounds good.

**Comment by the-emerald** [comment]
Looks like the PR never closed this issue!
